name: notify slack
description: notify slack from https://slack.com/api/chat.postMessage
author: Suguru Tanishima
inputs:
 token:
   description: 'token'
   required: true
 channel:
   description: 'channel'
   required: true
 icon_emoji:
   description: 'icon'
   default: ':thinking_face:'
 username:
   description: 'username'
   default: 'notify'
 text:
   description: 'text'
   default: ''
 attachments_color:
   description: 'attachments color'
   default: ''
 attachments_text:
   description: 'attachments text'
   default: ''
runs:
 using: docker
 image: Dockerfile
branding:
 icon: plus
 color: green
